name: Deploy to genezio
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: project
      - name: Setup Node.js
        uses: actions/setup-node@v3
        id: node
        with:
          node-version: 18
      - name: Setup genezio CLI
        uses: actions/checkout@v3
        with:
          repository: "Genez-io/genezio"
          ref: dev
          path: genezio
      - name: Deploy with genezio
        run: cd genezio && npm install && npm run install-locally-dev && genezio login ${{ secrets.GENEZIO_TOKEN }} && cd ../project && genezio deploy
